server:
  port: 8099

order.uri: http://order-svc:8011/order
product.uri: http://product-svc:8012/product
payment.uri:  http://payment-svc:8013/payment

spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: demo
  password: demo

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example: DEBUG